<a href="https://colab.research.google.com/github/jikrey123/data-analysis-journey/blob/main/DAY%2017.%20Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
#checking for the data structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [3]:
#missing values for each cell
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [4]:
#missing values for a large dataset
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
#finding the percentage of missing values
df.isnull().sum() * 100

PassengerId        0
Survived           0
Pclass             0
Name               0
Sex                0
Age            17700
SibSp              0
Parch              0
Ticket             0
Fare               0
Cabin          68700
Embarked         200
dtype: int64

In [6]:
#to remove passengers whose age is missing
df.dropna(subset=["Age"])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
#filling age with the median
df["Age"]= df["Age"].fillna(df["Age"].median())

In [8]:
#to check whether age is still missing
df["Age"].isnull().sum()

np.int64(0)

In [9]:
#finding duplicate rows
df.duplicated().sum()

np.int64(0)

In [10]:
#to remove duplicate rows
df = df.drop_duplicates()

In [11]:
#checking again for duplicates
df.duplicated().sum()

np.int64(0)

In [12]:
#checking data types
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [13]:
#HANDLING CATEGORICAL MISSING VALUES
df["Embarked"].isnull().sum()

np.int64(2)

In [14]:
# find existing categories
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [15]:
#we fill missing categorical values with mode
#finding mode
df["Embarked"].mode()[0]

'S'

In [16]:
#filling the missing values
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [17]:
#checking for missing values in embarked
df["Embarked"].isnull().sum()

np.int64(0)

In [18]:
#Understanding Cabin
df["Cabin"].isnull().sum()

np.int64(687)

In [19]:
#creating a new category
df["Cabin"] = df["Cabin"].fillna("Unknown")

In [20]:
#check for missing values
df["Cabin"].isnull().sum()

np.int64(0)

In [21]:
#FINDING SUSPICIOUS VALUES
# min and max can help us to spot unusual values
df["Age"].describe

<bound method NDFrame.describe of 0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64>

In [22]:
#CHECCKING CATEGORICAL INCONSISTENCES
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [23]:
df["Sex"] =df["Sex"].str.lower()

In [24]:
#REMOVING UNNECESSARY COLUMNS
#let us remove passenger id
df =df.drop(columns = ["PassengerId"])